### ISSUE TITLE
32-bit module - build from source? 

### ISSUE THREAD

**Issue by dennorske** [oohlaf/python-whirlpool#7]
Hello!

I am working on a project that requires whirlpool to compare hashes from a different system. Although I am strictly limited by the environment I run in, which is 32-bit python 3.8.6. 

I tried building from source with; `CFLAGS=-m32 LDFLAGS=-m32 python3.8 setup.py install` - although I had no luck, as it seem there's not expectations to build this with 32-bit.

Could I get some advice how to go forward to achieve this?

**Comment by oohlaf** [comment]
Hi,

Was not available last couple of days.
Are you still having issues? What was the error?

The Appveyor build for windows is 32bit and 64bit.
The Linux one was not, as Travis does not support it, if I remember well.

Regards,
Olaf

**Comment by dennorske** [comment]
Hi!
Sorry, it was my mistake. I had to install binaries to cross build over to 32 bit, and it worked flawlessly. `gcc-i686-linux-gnu` installed and problem solved :)
